# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import metrics.infgen.map_pb2 as map__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escenario.proto\x12\x0blong_metric\x1a\tmap.proto\"\xba\x01\n\x0bObjectState\x12\x10\n\x08\x63\x65nter_x\x18\x02 \x01(\x01\x12\x10\n\x08\x63\x65nter_y\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x65nter_z\x18\x04 \x01(\x01\x12\x0e\n\x06length\x18\x05 \x01(\x02\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\x12\x0f\n\x07heading\x18\x08 \x01(\x02\x12\x12\n\nvelocity_x\x18\t \x01(\x02\x12\x12\n\nvelocity_y\x18\n \x01(\x02\x12\r\n\x05valid\x18\x0b \x01(\x08\"\xd8\x01\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x32\n\x0bobject_type\x18\x02 \x01(\x0e\x32\x1d.long_metric.Track.ObjectType\x12(\n\x06states\x18\x03 \x03(\x0b\x32\x18.long_metric.ObjectState\"e\n\nObjectType\x12\x0e\n\nTYPE_UNSET\x10\x00\x12\x10\n\x0cTYPE_VEHICLE\x10\x01\x12\x13\n\x0fTYPE_PEDESTRIAN\x10\x02\x12\x10\n\x0cTYPE_CYCLIST\x10\x03\x12\x0e\n\nTYPE_OTHER\x10\x04\"K\n\x0f\x44ynamicMapState\x12\x38\n\x0blane_states\x18\x01 \x03(\x0b\x32#.long_metric.TrafficSignalLaneState\"\xa5\x01\n\x12RequiredPrediction\x12\x13\n\x0btrack_index\x18\x01 \x01(\x05\x12\x43\n\ndifficulty\x18\x02 \x01(\x0e\x32/.long_metric.RequiredPrediction.DifficultyLevel\"5\n\x0f\x44ifficultyLevel\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07LEVEL_1\x10\x01\x12\x0b\n\x07LEVEL_2\x10\x02\"\xdc\x02\n\x08Scenario\x12\x13\n\x0bscenario_id\x18\x05 \x01(\t\x12\x1a\n\x12timestamps_seconds\x18\x01 \x03(\x01\x12\x1a\n\x12\x63urrent_time_index\x18\n \x01(\x05\x12\"\n\x06tracks\x18\x02 \x03(\x0b\x32\x12.long_metric.Track\x12\x38\n\x12\x64ynamic_map_states\x18\x07 \x03(\x0b\x32\x1c.long_metric.DynamicMapState\x12-\n\x0cmap_features\x18\x08 \x03(\x0b\x32\x17.long_metric.MapFeature\x12\x17\n\x0fsdc_track_index\x18\x06 \x01(\x05\x12\x1b\n\x13objects_of_interest\x18\x04 \x03(\x05\x12:\n\x11tracks_to_predict\x18\x0b \x03(\x0b\x32\x1f.long_metric.RequiredPredictionJ\x04\x08\t\x10\n')



_OBJECTSTATE = DESCRIPTOR.message_types_by_name['ObjectState']
_TRACK = DESCRIPTOR.message_types_by_name['Track']
_DYNAMICMAPSTATE = DESCRIPTOR.message_types_by_name['DynamicMapState']
_REQUIREDPREDICTION = DESCRIPTOR.message_types_by_name['RequiredPrediction']
_SCENARIO = DESCRIPTOR.message_types_by_name['Scenario']
_TRACK_OBJECTTYPE = _TRACK.enum_types_by_name['ObjectType']
_REQUIREDPREDICTION_DIFFICULTYLEVEL = _REQUIREDPREDICTION.enum_types_by_name['DifficultyLevel']
ObjectState = _reflection.GeneratedProtocolMessageType('ObjectState', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTSTATE,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:long_metric.ObjectState)
  })
_sym_db.RegisterMessage(ObjectState)

Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), {
  'DESCRIPTOR' : _TRACK,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:long_metric.Track)
  })
_sym_db.RegisterMessage(Track)

DynamicMapState = _reflection.GeneratedProtocolMessageType('DynamicMapState', (_message.Message,), {
  'DESCRIPTOR' : _DYNAMICMAPSTATE,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:long_metric.DynamicMapState)
  })
_sym_db.RegisterMessage(DynamicMapState)

RequiredPrediction = _reflection.GeneratedProtocolMessageType('RequiredPrediction', (_message.Message,), {
  'DESCRIPTOR' : _REQUIREDPREDICTION,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:long_metric.RequiredPrediction)
  })
_sym_db.RegisterMessage(RequiredPrediction)

Scenario = _reflection.GeneratedProtocolMessageType('Scenario', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIO,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:long_metric.Scenario)
  })
_sym_db.RegisterMessage(Scenario)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTSTATE._serialized_start=43
  _OBJECTSTATE._serialized_end=229
  _TRACK._serialized_start=232
  _TRACK._serialized_end=448
  _TRACK_OBJECTTYPE._serialized_start=347
  _TRACK_OBJECTTYPE._serialized_end=448
  _DYNAMICMAPSTATE._serialized_start=450
  _DYNAMICMAPSTATE._serialized_end=525
  _REQUIREDPREDICTION._serialized_start=528
  _REQUIREDPREDICTION._serialized_end=693
  _REQUIREDPREDICTION_DIFFICULTYLEVEL._serialized_start=640
  _REQUIREDPREDICTION_DIFFICULTYLEVEL._serialized_end=693
  _SCENARIO._serialized_start=696
  _SCENARIO._serialized_end=1044
# @@protoc_insertion_point(module_scope)
