_target_: models.QCNet

dataset: argoverse_v2
input_dim: 2
hidden_dim: 128
output_dim: 2
output_head: false
num_historical_steps: ${datamodule.dataset.num_historical_steps}
num_future_steps: ${datamodule.dataset.num_future_steps}
num_modes: 6
num_recurrent_steps: 3
num_freq_bands: 4
num_map_layers: 2
num_agent_layers: 2
num_dec_layers: 2
num_heads: 8
head_dim: 16
pl2pl_radius: 80.0
time_span: 10
pl2a_radius: 60.0
a2a_radius: 40.0
num_t2m_steps: 10
pl2m_radius: 60.0
a2m_radius: 40.0
dropout: 0.1
weight_decay: 1e-4
T_max: 100
submission_dir: ${output_root_dir}
submission_file_name: submission
